### ISSUE TITLE
AMPALTagging Tutorial

### ISSUE THREAD

**Issue by ajasja** [woolfson-group/isambard#25]
When runing the tutorial I get the error 

`ImportError: No module named 'isambard.add_ons'`

![image](https://cloud.githubusercontent.com/assets/19926/21644257/eb74d55a-d28c-11e6-94af-56ee0bd1fac1.png)

I also can not find `convert_pdb_to_assembly` and `tag_socket` in the code.

**Comment by ChrisWellsWood** [comment]
Good spot, they aren't in this version yet. I'll remove that tutorial.

**Comment by ajasja** [comment]
Hmm, could you push the socket tagging code in to the release repo? I'd
like to be able to assign registers based on structure...

**Comment by ChrisWellsWood** [comment]
It's not ready yet, I'll talk to you about it on Skype.
