### ISSUE TITLE
import isambard error

### ISSUE THREAD

**Issue by ever4cyth** [woolfson-group/isambard#28]
import isambard
ValueError                                Traceback (most recent call last)
<ipython-input-1-ecf256aec169> in <module>()
----> 1 import isambard

/home/python/lib/python2.7/site-packages/isambard/__init__.py in <module>()
     10 
     11 try:
---> 12     from settings import global_settings
     13     import settings
     14     import ampal

/home/python/lib/python2.7/site-packages/isambard/settings.py in <module>()
     46     configure()
     47 else:
---> 48     load_global_settings()
     49 
     50 

/home/python/lib/python2.7/site-packages/isambard/settings.py in load_global_settings()
     31     with open(settings_path, 'r') as settings_f:
     32         global global_settings
---> 33         settings_json = json.loads(settings_f.read())
     34         if global_settings is None:
     35             global_settings = settings_json

/usr/lib/python2.7/json/__init__.pyc in loads(s, encoding, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    336             parse_int is None and parse_float is None and
    337             parse_constant is None and object_pairs_hook is None and not kw):
--> 338         return _default_decoder.decode(s)
    339     if cls is None:
    340         cls = JSONDecoder

/usr/lib/python2.7/json/decoder.pyc in decode(self, s, _w)
    364 
    365         """
--> 366         obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    367         end = _w(s, end).end()
    368         if end != len(s):

/usr/lib/python2.7/json/decoder.pyc in raw_decode(self, s, idx)
    382             obj, end = self.scan_once(s, idx)
    383         except StopIteration:
--> 384             raise ValueError("No JSON object could be decoded")
    385         return obj, end

ValueError: No JSON object could be decoded

**Comment by ChrisWellsWood** [comment]
It looks like you're using Python 2.7, which will cause problems as we use a bunch of Python 3 features. Could you also check that you have a `.isambard_settings.json` file in your home directory, you should have been promoted  to enter some settings during your initial import.

**Comment by ever4cyth** [comment]
Thanks for your reply. I switched to python 3.4. I actually didn't get promoted to enter settings. so I made a empty file .isambard_settings in my home directory. below is the error message. if I change name to .isambard_settings.json, I got a different error message.

ValueError                                Traceback (most recent call last)
<ipython-input-3-ecf256aec169> in <module>()
----> 1 import isambard

~/python3/lib/python3.4/site-packages/isambard/__init__.py in <module>()
     10 
     11 try:
---> 12     from settings import global_settings
     13     import settings
     14     import ampal

~/python3/lib/python3.4/site-packages/isambard/settings.py in <module>()
     46     configure()
     47 else:
---> 48     load_global_settings()
     49 
     50 

~/python3/lib/python3.4/site-packages/isambard/settings.py in load_global_settings()
     31     with open(settings_path, 'r') as settings_f:
     32         global global_settings
---> 33         settings_json = json.loads(settings_f.read())
     34         if global_settings is None:
     35             global_settings = settings_json

/usr/lib/python3.4/json/__init__.py in loads(s, encoding, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    316             parse_int is None and parse_float is None and
    317             parse_constant is None and object_pairs_hook is None and not kw):
--> 318         return _default_decoder.decode(s)
    319     if cls is None:
    320         cls = JSONDecoder

/usr/lib/python3.4/json/decoder.py in decode(self, s, _w)
    341 
    342         """
--> 343         obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    344         end = _w(s, end).end()
    345         if end != len(s):

/usr/lib/python3.4/json/decoder.py in raw_decode(self, s, idx)
    359             obj, end = self.scan_once(s, idx)
    360         except StopIteration as err:
--> 361             raise ValueError(errmsg("Expecting value", s, err.value)) from None
    362         return obj, end

ValueError: Expecting value: line 1 column 1 (char 0)

**Comment by ChrisWellsWood** [comment]
You're right, it should be `.isambard_settings`, no `.json` at the end. I'm really struggling to recreate this error, could you let me know:

1. The platform you're running ISAMBARD on
1. How you installed ISAMBARD (through pip or from source)

You could try a couple of things in the meantime:

1. We recommend using the Anaconda Python package, and we test all code with 3.5 and 3.6
1. If for some reason you can't use Anaconda on your system, make sure you update all your Python packages with PIP.
1. Try running [`configure.py`](https://github.com/woolfson-group/isambard/blob/master/isambard/configure.py) directly, it's located in the ISAMBARD module folder.

**Comment by ever4cyth** [comment]
Ubuntu 14.04, installed ISAMBARD through pip.

Run configure.py, maybe this is what the problem is?

python configure.py 
Traceback (most recent call last):
  File "configure.py", line 7, in <module>
    import readline
  File "/home/python3/lib/python3.4/site-packages/readline.py", line 6, in <module>
    from pyreadline.rlmain import Readline
  File "/home/python3/lib/python3.4/site-packages/pyreadline/__init__.py", line 12, in <module>
    from . import logger, clipboard, lineeditor, modes, console
  File "/home/python3/lib/python3.4/site-packages/pyreadline/clipboard/__init__.py", line 13, in <module>
    from .win32_clipboard import GetClipboardText, SetClipboardText
  File "/home/python3/lib/python3.4/site-packages/pyreadline/clipboard/win32_clipboard.py", line 37, in <module>
    import ctypes.wintypes as wintypes
  File "/usr/lib/python2.7/ctypes/wintypes.py", line 23, in <module>
    class VARIANT_BOOL(_SimpleCData):
ValueError: _type_ 'v' not supported

**Comment by ChrisWellsWood** [comment]
I don't think this is an issue with ISAMBARD, it looks like theres a problem with the `pyreadline` module on your system. This module is in the configuration script. My colleague pointed out that the error you're getting in the last line of your traceback is still complaining about Python 2.7:

```
File "/usr/lib/python2.7/ctypes/wintypes.py", line 23, in 
class VARIANT_BOOL(_SimpleCData):
ValueError: type 'v' not supported
```

It looks like Python is looking for your packages in the wrong place. ISAMBARD definitely works on Ubuntu, our [CI platform](https://circleci.com/gh/woolfson-group/isambard) uses Ubuntu for automatically testing our code. **The best course of action would be to install the [Anaconda Python](https://www.continuum.io/downloads) package.** This is very easy, and can be system wide or limited to only your account, which is great if you don't want to interfere with the system version of Python. It also simplifies creating [virtual environments](https://conda.io/docs/using/envs.html), even across different versions of Python, if you need to isolate your code further.

**Comment by ever4cyth** [comment]
same error after I fix the PYTHONPATH

python3 configure.py 
Traceback (most recent call last):
  File "configure.py", line 7, in <module>
    import readline
  File "/home/python3/lib/python3.4/site-packages/readline.py", line 6, in <module>
    from pyreadline.rlmain import Readline
  File "/home/python3/lib/python3.4/site-packages/pyreadline/__init__.py", line 12, in <module>
    from . import logger, clipboard, lineeditor, modes, console
  File "/home/python3/lib/python3.4/site-packages/pyreadline/clipboard/__init__.py", line 13, in <module>
    from .win32_clipboard import GetClipboardText, SetClipboardText
  File "/home/python3/lib/python3.4/site-packages/pyreadline/clipboard/win32_clipboard.py", line 37, in <module>
    import ctypes.wintypes as wintypes
  File "/usr/lib/python3.4/ctypes/wintypes.py", line 20, in <module>
    class VARIANT_BOOL(ctypes._SimpleCData):
ValueError: _type_ 'v' not supported

**Comment by ChrisWellsWood** [comment]
This is a weird line:

`import ctypes.wintypes as wintypes`

This should only be running on Windows... `import readline` should not be trying to import `pyreadline` on Unix systems. Maybe try:

```
pip uninstall pyreadline
pip uninstall readline
pip install readline
```

This isn't an issue with ISAMBARD, this seems to be an issue with your environment.
